# Generated by Django 5.0.6 on 2024-05-23 19:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ListOfRules',
            fields=[
                ('obligation', models.TextField()),
                ('comment', models.TextField()),
                ('ae_source_countries', models.TextField()),
                ('receiver', models.TextField()),
                ('format', models.TextField()),
                ('other_procedures', models.TextField()),
                ('type_of_event', models.TextField()),
                ('valid_start_date', models.DateField()),
                ('valid_end_date', models.DateField()),
                ('deadline_to_submit', models.TextField()),
                ('link_from_names', models.BigIntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='NameOfMedicaments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('link_to_rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.listofrules')),
            ],
        ),
    ]
