# Generated by Django 5.0.6 on 2024-05-26 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('error_percentage', models.FloatField(default=50.0, help_text='Allowed error percentage for Levenshtein search')),
            ],
        ),
    ]
