# Generated by Django 5.0.6 on 2024-05-26 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_searchsettings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='searchsettings',
            name='error_percentage',
        ),
        migrations.AddField(
            model_name='searchsettings',
            name='allowed_error_percentage',
            field=models.FloatField(default=50.0),
        ),
    ]
